version: '3.8' # Просто версия синтаксиса, не трогаем

services: # Список "сервисов" (коробок), которые мы хотим запустить
  
  postgres-db: # Название нашего сервиса, можно дать любое
    image: postgres:15-alpine # "Волшебная коробка". Мы просим Docker скачать образ Postgres 15
    restart: always # Всегда перезапускать, если он упадет
    environment: # Здесь мы настраиваем нашу БД
      - POSTGRES_USER=myuser         # Имя пользователя для подключения
      - POSTGRES_PASSWORD=mypassword # Пароль для подключения
      - POSTGRES_DB=mydb             # Название базы данных, которая будет создана
    ports: # Пробрасываем порт из "коробки" на наш компьютер
      - "5432:5432" # "Сделай порт 5432 изнутри коробки доступным на порту 5432 снаружи"